# Generated by Django 6.0.7 on 2026-07-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payments_link_payments_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_date",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="Дата платежа"
            ),
        ),
    ]
