# Generated by Django 6.0.7 on 2026-07-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_alter_lesson_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Последнее обновление курса"
            ),
        ),
    ]
